services:
  cms:
    image: traefik/whoami
    container_name: cms
    env_file: .env
    labels:
      traefik.enable: true
      traefik.docker.network: ${SHARED_NETWORK}
      # router
      traefik.http.routers.cms.service: cms
      traefik.http.routers.cms.entrypoints: websecure
      traefik.http.routers.cms.middlewares: "default@file"
      traefik.http.routers.cms.rule: Host(`${CMS_HOST:?err}`)
      traefik.http.routers.cms.tls.certresolver: "letsencrypt"
      traefik.http.routers.cms.tls.options: "modern@file"
      traefik.http.routers.cms.tls: true
      # service
      traefik.http.services.cms.loadBalancer.server.port: 80
      traefik.http.services.cms.loadBalancer.sticky.cookie.httpOnly: true
      traefik.http.services.cms.loadBalancer.sticky.cookie.secure: true
      traefik.http.services.cms.loadBalancer.sticky.cookie.name: cms_sticky
      traefik.http.services.cms.loadBalancer.sticky.cookie: true

    networks:
      - shared
    restart: always

networks:
  shared:
    external: true
    name: ${SHARED_NETWORK}
