# Traefik static configuration file (/etc/traefik/traefik.yml)
# See https://doc.traefik.io/traefik/getting-started/configuration-overview/#the-static-configuration
# and https://doc.traefik.io/traefik/reference/static-configuration/cli/

global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  filePath: "/logs/traefik.log"
  level: DEBUG
  maxSize: 2
  maxBackups: 3
  maxAge: 3
  compress: true

accessLog:
  filePath: "/logs/access.log"
  addInternals: true
  bufferingSize: 100
  fields:
    headers:
      names:
        User-Agent: keep

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
        #permanent: true

  websecure:
    address: ":443"
    http:
      tls:
        certresolver: letsencrypt

  tcp:
    address: ":5432"

  db:
    address: ":5050"

  cms:
    address: ":1337"

  analytics:
    address: ":3000"


providers:
  # can read labels from Docker services
  docker:
    endpoint: "unix:///var/run/docker.sock"
    # do not expose Docker containers unless explicitly exposed via label "traefik.enable=true"
    exposedByDefault: false

  file:
    directory: /etc/traefik
    watch: true

  providersThrottleDuration: 10               # Configuration reload frequency

# Certificate Resolvers are responsible for retrieving certificates from an ACME server
# See https://doc.traefik.io/traefik/https/acme/#certificate-resolvers
certificatesResolvers:
  # Enable ACME (Let's Encrypt): automatic SSL.
  letsencrypt:
    acme:
      #email: "${CERT_EMAIL}" # Email address used for registration
      storage: /etc/certs/acme.json # File or key used for certificates storage
      caServer: https://acme-v02.api.letsencrypt.org/directory # prod
      #caServer: https://acme-staging-v02.api.letsencrypt.org/directory # staging
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
        delayBeforeCheck: 20